# Generated by Django 3.0.4 on 2020-04-08 02:58

import crawler.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='关键字')),
            ],
            options={
                'verbose_name': '关键字',
                'verbose_name_plural': '关键字',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('scanned_images_count', models.IntegerField(blank=True, null=True, verbose_name='图片扫描数量')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='crawler.Keyword', verbose_name='关键字')),
            ],
            options={
                'verbose_name': '任务',
                'verbose_name_plural': '任务',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(blank=True, max_length=128, null=True)),
                ('md5', models.CharField(max_length=32, unique=True, verbose_name='MD5')),
                ('status', models.BooleanField(blank=True, null=True, verbose_name='筛选状态')),
                ('image_file', models.ImageField(upload_to=crawler.models.get_image_dir, verbose_name='图片')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='images', to='crawler.Keyword', verbose_name='关键字')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='images', to='crawler.Task', verbose_name='任务')),
            ],
            options={
                'verbose_name': '图片',
                'verbose_name_plural': '图片',
            },
        ),
    ]
