# Generated by Django 3.0.4 on 2020-04-02 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crawler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=16)),
                ('status', models.BooleanField()),
                ('browser_version', models.CharField(max_length=32)),
                ('driver_version', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=16, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('engine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='crawler.Engine')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='keywords', to='crawler.Keyword')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('file_path', models.CharField(max_length=128)),
                ('md5', models.CharField(max_length=32, unique=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='images', to='crawler.Task')),
            ],
        ),
    ]
