# Generated by Django 3.0.4 on 2020-04-02 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='engine',
        ),
        migrations.DeleteModel(
            name='Engine',
        ),
    ]
