# Generated by Django 3.0.4 on 2020-04-10 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0002_spider'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spider',
            options={'verbose_name': '爬虫', 'verbose_name_plural': '爬虫'},
        ),
        migrations.AddField(
            model_name='task',
            name='spider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='crawler.Spider', verbose_name='爬虫'),
            preserve_default=False,
        ),
    ]
