# Generated by Django 3.0.4 on 2020-04-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0003_auto_20200403_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
