# Generated by Django 3.0.4 on 2020-04-10 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0003_auto_20200410_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='spider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='crawler.Spider', verbose_name='爬虫'),
        ),
    ]
