# Generated by Django 3.0.4 on 2020-04-10 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0004_auto_20200410_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='crawler.Task', verbose_name='任务'),
        ),
    ]
